import { useEffect, useState } from "react"
import { BellRing, LoaderCircle, Smartphone, Trash2 } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { ApiError } from "@/lib/api"
import { applicationServerKey, getPushConfig, removePushSubscription, savePushSubscription, type PushConfig } from "@/lib/notification-api"

export function PushSettings({ readOnly }: { readOnly: boolean }) {
  const [config, setConfig] = useState<PushConfig | null>(null), [working, setWorking] = useState(false), [error, setError] = useState("")
  const load = () => getPushConfig().then(setConfig).catch((reason) => setError(reason instanceof ApiError ? reason.message : "Push settings could not be loaded."))
  useEffect(() => { const controller = new AbortController(); getPushConfig(controller.signal).then(setConfig).catch((reason) => { if (!controller.signal.aborted) setError(reason instanceof ApiError ? reason.message : "Push settings could not be loaded.") }); return () => controller.abort() }, [])
  async function enable() { setWorking(true); setError(""); try { if (!("serviceWorker" in navigator) || !("PushManager" in window)) throw new Error("This browser does not support Web Push."); const permission = await Notification.requestPermission(); if (permission !== "granted") throw new Error("Notification permission was not granted."); const registration = await navigator.serviceWorker.ready; const existing = await registration.pushManager.getSubscription(); const subscription = existing ?? await registration.pushManager.subscribe({ userVisibleOnly: true, applicationServerKey: applicationServerKey(config?.publicKey ?? "") as BufferSource }); await savePushSubscription(subscription); await load() } catch (reason) { setError(reason instanceof Error ? reason.message : "Web Push could not be enabled.") } finally { setWorking(false) } }
  async function remove(id: string) { setWorking(true); setError(""); try { await removePushSubscription(id); await load() } catch (reason) { setError(reason instanceof ApiError ? reason.message : "The device could not be removed.") } finally { setWorking(false) } }
  return <Card><CardHeader><div><CardTitle>Browser notifications</CardTitle><p className="mt-1 text-sm text-muted-foreground">Receive reminders even when the dashboard is closed.</p></div><BellRing className="size-5 text-muted-foreground" /></CardHeader><CardContent className="space-y-4">{error && <p role="alert" className="rounded-md border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}{config && !config.supported && <p className="text-sm text-amber-700">Web Push needs VAPID keys configured on the Worker before devices can subscribe.</p>}{config?.devices.map((device) => <div key={device.id} className="flex items-center gap-3 rounded-lg border p-3"><Smartphone className="size-5 text-primary" /><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{device.name}</p><p className="text-xs text-muted-foreground">Added {new Date(device.createdAt * 1000).toLocaleDateString("en-AU")}</p></div><Button variant="ghost" size="icon" disabled={working || readOnly} onClick={() => remove(device.id)} aria-label="Remove notification device"><Trash2 className="size-4" /></Button></div>)}<Button disabled={working || readOnly || !config?.supported} onClick={enable}>{working && <LoaderCircle className="size-4 animate-spin" />}{config?.enabled ? "Add this device" : "Enable Web Push"}</Button><p className="text-xs leading-5 text-muted-foreground">On iPhone or iPad, install the dashboard on the Home Screen before enabling notifications.</p></CardContent></Card>
}
