import { useEffect, useMemo, useState, type FormEvent } from "react"
import { AlarmClock, Ban, LoaderCircle, Pencil, Plus, RotateCcw, Search, Trash2, X } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { ApiError } from "@/lib/api"
import { createReminder, deleteReminder, getReminders, updateReminder, type Reminder, type ReminderInput } from "@/lib/reminder-api"
import { getSettings } from "@/lib/settings-api"

type Filter = "pending" | "cancelled" | "all"
const timezone = Intl.DateTimeFormat().resolvedOptions().timeZone || "Australia/Brisbane"
const empty = (preferredTimezone = timezone): ReminderInput => ({ title: "", dueAt: Math.floor(Date.now() / 1000) + 3600, timezone: preferredTimezone, recurrence: "none" })
const fieldClass = "h-11 w-full rounded-md border bg-background px-3 text-sm outline-none focus-visible:ring-2 focus-visible:ring-ring"
function inputDate(seconds: number) { const date = new Date(seconds * 1000); const offset = date.getTimezoneOffset() * 60_000; return new Date(date.getTime() - offset).toISOString().slice(0, 16) }

export function RemindersPage({ readOnly }: { readOnly: boolean }) {
  const [items, setItems] = useState<Reminder[]>([]), [loading, setLoading] = useState(true), [saving, setSaving] = useState(false)
  const [showForm, setShowForm] = useState(false), [editingId, setEditingId] = useState<string | null>(null), [draft, setDraft] = useState<ReminderInput>(empty)
  const [preferredTimezone, setPreferredTimezone] = useState(timezone)
  const [filter, setFilter] = useState<Filter>("pending"), [search, setSearch] = useState(""), [error, setError] = useState("")
  useEffect(() => { const controller = new AbortController(); getSettings(controller.signal).then((value) => { setPreferredTimezone(value.timezone); setDraft((current) => ({ ...current, timezone: value.timezone })) }).catch(() => {}); return () => controller.abort() }, [])
  useEffect(() => { const controller = new AbortController(); getReminders(controller.signal).then(setItems).catch((reason) => { if (!controller.signal.aborted) setError(reason instanceof ApiError ? reason.message : "Reminders could not be loaded.") }).finally(() => { if (!controller.signal.aborted) setLoading(false) }); return () => controller.abort() }, [])
  const visible = useMemo(() => items.filter((item) => (filter === "all" || item.status === filter) && item.title.toLowerCase().includes(search.trim().toLowerCase())), [items, filter, search])
  function openNew() { setEditingId(null); setDraft(empty(preferredTimezone)); setShowForm(true); setError("") }
  function openEdit(item: Reminder) { setEditingId(item.id); setDraft({ title: item.title, dueAt: item.dueAt, timezone: item.timezone, recurrence: item.recurrence }); setShowForm(true); setError("") }
  function close() { setShowForm(false); setEditingId(null); setDraft(empty(preferredTimezone)) }
  async function save(event: FormEvent) { event.preventDefault(); setSaving(true); setError(""); try { if (editingId) { const updated = await updateReminder(editingId, draft); setItems((current) => current.map((item) => item.id === editingId ? updated : item).sort((a, b) => a.dueAt - b.dueAt)) } else { const created = await createReminder(draft); setItems((current) => [...current, created].sort((a, b) => a.dueAt - b.dueAt)) } close() } catch (reason) { setError(reason instanceof ApiError ? reason.message : "The reminder could not be saved.") } finally { setSaving(false) } }
  async function setStatus(item: Reminder) { setError(""); try { const updated = await updateReminder(item.id, { status: item.status === "cancelled" ? "pending" : "cancelled" }); setItems((current) => current.map((value) => value.id === item.id ? updated : value)) } catch (reason) { setError(reason instanceof ApiError ? reason.message : "The reminder could not be updated.") } }
  async function remove(item: Reminder) { if (!window.confirm(`Delete “${item.title}”?`)) return; setError(""); try { await deleteReminder(item.id); setItems((current) => current.filter((value) => value.id !== item.id)) } catch (reason) { setError(reason instanceof ApiError ? reason.message : "The reminder could not be deleted.") } }
  return <div className="space-y-5">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-center"><div className="relative flex-1"><Search className="absolute left-3 top-3.5 size-4 text-muted-foreground" /><input aria-label="Search reminders" placeholder="Search reminders" value={search} onChange={(event) => setSearch(event.target.value)} className={`${fieldClass} pl-9`} /></div>{!readOnly && <Button onClick={openNew}><Plus className="size-4" />New reminder</Button>}</div>
    <div className="flex gap-1 rounded-lg bg-muted p-1" role="group" aria-label="Filter reminders">{(["pending", "cancelled", "all"] as Filter[]).map((value) => <Button key={value} variant={filter === value ? "default" : "ghost"} size="sm" onClick={() => setFilter(value)} className="flex-1 capitalize sm:flex-none">{value}</Button>)}</div>
    {readOnly && <p className="rounded-md border bg-muted/40 p-3 text-sm text-muted-foreground">This account can view reminders but cannot change them.</p>}{error && <p role="alert" className="rounded-md border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}
    {showForm && <Card><CardContent className="pt-6"><form onSubmit={save} className="grid gap-4"><div><label htmlFor="reminder-title" className="mb-2 block text-sm font-medium">Title</label><input id="reminder-title" required maxLength={200} autoFocus value={draft.title} onChange={(event) => setDraft({ ...draft, title: event.target.value })} className={fieldClass} /></div><div className="grid gap-4 md:grid-cols-3"><div><label htmlFor="reminder-due" className="mb-2 block text-sm font-medium">Date and time</label><input id="reminder-due" type="datetime-local" required value={inputDate(draft.dueAt)} onChange={(event) => setDraft({ ...draft, dueAt: Math.floor(new Date(event.target.value).getTime() / 1000) })} className={fieldClass} /></div><div><label htmlFor="reminder-timezone" className="mb-2 block text-sm font-medium">Timezone</label><input id="reminder-timezone" required maxLength={100} value={draft.timezone} onChange={(event) => setDraft({ ...draft, timezone: event.target.value })} className={fieldClass} /></div><div><label htmlFor="reminder-recurrence" className="mb-2 block text-sm font-medium">Repeat</label><select id="reminder-recurrence" value={draft.recurrence} onChange={(event) => setDraft({ ...draft, recurrence: event.target.value as Reminder["recurrence"] })} className={fieldClass}><option value="none">Does not repeat</option><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option></select></div></div><div className="flex justify-end gap-2"><Button type="button" variant="ghost" onClick={close}><X className="size-4" />Cancel</Button><Button type="submit" disabled={saving || !draft.title.trim()}>{saving && <LoaderCircle className="size-4 animate-spin" />}{saving ? "Saving…" : editingId ? "Save changes" : "Add reminder"}</Button></div></form></CardContent></Card>}
    {loading ? <div className="grid min-h-48 place-items-center"><LoaderCircle className="size-6 animate-spin text-primary" aria-label="Loading reminders" /></div> : visible.length === 0 ? <Card><CardContent className="flex min-h-48 flex-col items-center justify-center text-center"><AlarmClock className="mb-4 size-6 text-muted-foreground" /><p className="font-medium">No matching reminders</p><p className="mt-2 text-sm text-muted-foreground">Schedule something important so it stays on your radar.</p></CardContent></Card> : <div className="space-y-3">{visible.map((item) => { const overdue = item.status === "pending" && item.dueAt < Date.now() / 1000; return <Card key={item.id}><CardContent className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center"><div className={`grid size-10 shrink-0 place-items-center rounded-full ${item.status === "cancelled" ? "bg-muted text-muted-foreground" : overdue ? "bg-red-100 text-red-700" : "bg-accent text-primary"}`}><AlarmClock className="size-5" /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className={`font-medium ${item.status === "cancelled" ? "line-through text-muted-foreground" : ""}`}>{item.title}</p>{item.recurrence !== "none" && <span className="rounded-full bg-muted px-2 py-0.5 text-xs capitalize">{item.recurrence}</span>}</div><p className={`mt-1 text-sm ${overdue ? "font-medium text-red-600" : "text-muted-foreground"}`}>{overdue ? "Overdue · " : ""}{new Date(item.dueAt * 1000).toLocaleString("en-AU", { dateStyle: "medium", timeStyle: "short" })} · {item.timezone}</p></div>{!readOnly && <div className="flex justify-end"><Button variant="ghost" size="icon" onClick={() => openEdit(item)} aria-label={`Edit ${item.title}`}><Pencil className="size-4" /></Button><Button variant="ghost" size="icon" onClick={() => setStatus(item)} aria-label={item.status === "cancelled" ? `Restore ${item.title}` : `Cancel ${item.title}`}>{item.status === "cancelled" ? <RotateCcw className="size-4" /> : <Ban className="size-4" />}</Button><Button variant="ghost" size="icon" onClick={() => remove(item)} aria-label={`Delete ${item.title}`}><Trash2 className="size-4" /></Button></div>}</CardContent></Card> })}</div>}
  </div>
}
