import { useEffect, useMemo, useState } from "react"
import { AlarmClock, CalendarDays, CheckSquare2, ChevronLeft, ChevronRight, LoaderCircle } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { ApiError } from "@/lib/api"
import { getSchedule, type ScheduleEvent } from "@/lib/schedule-api"
import { getSettings } from "@/lib/settings-api"

type Kind = "task" | "reminder"
const dayKey = (date: Date) => `${date.getFullYear()}-${date.getMonth()}-${date.getDate()}`
function monthRange(month: Date, weekStartsOn: 0 | 1) { const start = new Date(month.getFullYear(), month.getMonth(), 1); const gridStart = new Date(start); gridStart.setDate(start.getDate() - ((start.getDay() - weekStartsOn + 7) % 7)); const gridEnd = new Date(gridStart); gridEnd.setDate(gridStart.getDate() + 42); return { start: Math.floor(gridStart.getTime() / 1000), end: Math.floor(gridEnd.getTime() / 1000), gridStart } }

export function SchedulePage() {
  const [month, setMonth] = useState(() => new Date(new Date().getFullYear(), new Date().getMonth(), 1))
  const [events, setEvents] = useState<ScheduleEvent[]>([]), [loading, setLoading] = useState(true), [error, setError] = useState("")
  const [kinds, setKinds] = useState<Set<Kind>>(() => new Set(["task", "reminder"]))
  const [weekStartsOn, setWeekStartsOn] = useState<0 | 1>(1)
  const range = useMemo(() => monthRange(month, weekStartsOn), [month, weekStartsOn])
  useEffect(() => { const controller = new AbortController(); getSettings(controller.signal).then((value) => setWeekStartsOn(value.weekStartsOn)).catch(() => {}); return () => controller.abort() }, [])
  useEffect(() => { const controller = new AbortController(); setLoading(true); setError(""); getSchedule(range.start, range.end, controller.signal).then(setEvents).catch((reason) => { if (!controller.signal.aborted) setError(reason instanceof ApiError ? reason.message : "The schedule could not be loaded.") }).finally(() => { if (!controller.signal.aborted) setLoading(false) }); return () => controller.abort() }, [range.start, range.end])
  const filtered = useMemo(() => events.filter((event) => kinds.has(event.type)), [events, kinds])
  const byDay = useMemo(() => { const map = new Map<string, ScheduleEvent[]>(); for (const event of filtered) { const key = dayKey(new Date(event.startsAt * 1000)); map.set(key, [...(map.get(key) ?? []), event]) } return map }, [filtered])
  const days = useMemo(() => Array.from({ length: 42 }, (_, index) => { const date = new Date(range.gridStart); date.setDate(date.getDate() + index); return date }), [range.gridStart])
  const today = dayKey(new Date()), now = Date.now() / 1000
  const upcoming = filtered.filter((event) => event.startsAt >= Math.floor(new Date(month.getFullYear(), month.getMonth(), 1).getTime() / 1000)).slice(0, 12)
  function toggle(kind: Kind) { setKinds((current) => { const next = new Set(current); if (next.has(kind)) next.delete(kind); else next.add(kind); return next }) }
  function shift(amount: number) { setMonth((current) => new Date(current.getFullYear(), current.getMonth() + amount, 1)) }
  return <div className="space-y-5">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-2"><Button variant="outline" size="icon" onClick={() => shift(-1)} aria-label="Previous month"><ChevronLeft className="size-4" /></Button><Button variant="outline" onClick={() => setMonth(new Date(new Date().getFullYear(), new Date().getMonth(), 1))}>Today</Button><Button variant="outline" size="icon" onClick={() => shift(1)} aria-label="Next month"><ChevronRight className="size-4" /></Button></div><h2 className="text-xl font-semibold">{month.toLocaleDateString("en-AU", { month: "long", year: "numeric" })}</h2><div className="flex gap-2"><Button variant={kinds.has("task") ? "default" : "outline"} size="sm" onClick={() => toggle("task")}><CheckSquare2 className="size-4" />Tasks</Button><Button variant={kinds.has("reminder") ? "default" : "outline"} size="sm" onClick={() => toggle("reminder")}><AlarmClock className="size-4" />Reminders</Button></div></div>
    {error && <p role="alert" className="rounded-md border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}
    <Card className="overflow-hidden"><CardContent className="p-0"><div className="grid grid-cols-7 border-b bg-muted/50 text-center text-xs font-medium text-muted-foreground">{(weekStartsOn === 1 ? ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"] : ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"]).map((day) => <div key={day} className="p-2">{day}</div>)}</div>{loading ? <div className="grid min-h-96 place-items-center"><LoaderCircle className="size-6 animate-spin text-primary" aria-label="Loading schedule" /></div> : <div className="grid grid-cols-7">{days.map((date) => { const key = dayKey(date), items = byDay.get(key) ?? [], activeMonth = date.getMonth() === month.getMonth(); return <div key={key} className={`min-h-24 border-b border-r p-1.5 sm:min-h-32 sm:p-2 ${activeMonth ? "bg-card" : "bg-muted/30 text-muted-foreground"}`}><div className={`mb-1 grid size-7 place-items-center rounded-full text-xs ${key === today ? "bg-primary font-semibold text-primary-foreground" : ""}`}>{date.getDate()}</div><div className="space-y-1">{items.slice(0, 3).map((event) => { const overdue = event.status === "pending" && event.startsAt < now; return <a key={`${event.type}-${event.id}`} href={`#${event.type === "task" ? "tasks" : "reminders"}`} className={`block truncate rounded px-1.5 py-1 text-[10px] leading-tight sm:text-xs ${event.type === "task" ? "bg-blue-100 text-blue-800" : "bg-amber-100 text-amber-800"} ${overdue ? "ring-1 ring-red-400" : ""}`} title={event.title}>{event.type === "reminder" && new Date(event.startsAt * 1000).toLocaleTimeString("en-AU", { hour: "numeric", minute: "2-digit" }) + " · "}{event.title}</a>})}{items.length > 3 && <p className="px-1 text-[10px] text-muted-foreground">+{items.length - 3} more</p>}</div></div> })}</div>}</CardContent></Card>
    <Card><CardHeader><CardTitle>Upcoming this month</CardTitle></CardHeader><CardContent>{!loading && upcoming.length === 0 ? <div className="flex min-h-32 flex-col items-center justify-center text-center"><CalendarDays className="mb-3 size-6 text-muted-foreground" /><p className="text-sm font-medium">Nothing scheduled</p><p className="mt-1 text-sm text-muted-foreground">Add due dates to tasks or create a reminder.</p></div> : <div className="divide-y">{upcoming.map((event) => <a key={`${event.type}-${event.id}`} href={`#${event.type === "task" ? "tasks" : "reminders"}`} className="flex items-center gap-3 py-3 first:pt-0 last:pb-0"><div className={`grid size-9 shrink-0 place-items-center rounded-lg ${event.type === "task" ? "bg-blue-100 text-blue-700" : "bg-amber-100 text-amber-700"}`}>{event.type === "task" ? <CheckSquare2 className="size-4" /> : <AlarmClock className="size-4" />}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{event.title}</p><p className="text-xs text-muted-foreground">{new Date(event.startsAt * 1000).toLocaleString("en-AU", { dateStyle: "medium", timeStyle: event.type === "reminder" ? "short" : undefined })}</p></div><span className="text-xs capitalize text-muted-foreground">{event.type}</span></a>)}</div>}</CardContent></Card>
  </div>
}
