import { useEffect, useState, type FormEvent } from "react"
import { Check, Clock3, LoaderCircle, Settings2, ShieldCheck, UserRound } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { ApiError, type Session } from "@/lib/api"
import { getSettings, updateSettings, type Settings } from "@/lib/settings-api"

const commonTimezones = ["Australia/Brisbane", "Australia/Sydney", "Australia/Melbourne", "Australia/Adelaide", "Australia/Perth", "Pacific/Auckland", "Asia/Kolkata", "Asia/Singapore", "Europe/London", "America/New_York", "America/Los_Angeles", "UTC"]
const fieldClass = "h-11 w-full rounded-md border bg-background px-3 text-sm outline-none focus-visible:ring-2 focus-visible:ring-ring"

export function SettingsPage({ session }: { session: Session }) {
  const [settings, setSettings] = useState<Settings | null>(null), [draft, setDraft] = useState<Settings | null>(null)
  const [loading, setLoading] = useState(true), [saving, setSaving] = useState(false), [error, setError] = useState(""), [saved, setSaved] = useState(false)
  useEffect(() => { const controller = new AbortController(); getSettings(controller.signal).then((value) => { setSettings(value); setDraft(value) }).catch((reason) => { if (!controller.signal.aborted) setError(reason instanceof ApiError ? reason.message : "Settings could not be loaded.") }).finally(() => { if (!controller.signal.aborted) setLoading(false) }); return () => controller.abort() }, [])
  async function save(event: FormEvent) { event.preventDefault(); if (!draft) return; setSaving(true); setSaved(false); setError(""); try { const value = await updateSettings({ timezone: draft.timezone, weekStartsOn: draft.weekStartsOn, defaultTaskPriority: draft.defaultTaskPriority }); setSettings(value); setDraft(value); setSaved(true); window.setTimeout(() => setSaved(false), 2500) } catch (reason) { setError(reason instanceof ApiError ? reason.message : "Settings could not be saved.") } finally { setSaving(false) } }
  if (loading) return <div className="grid min-h-72 place-items-center"><LoaderCircle className="size-6 animate-spin text-primary" aria-label="Loading settings" /></div>
  return <div className="grid gap-5 lg:grid-cols-[minmax(0,2fr)_minmax(18rem,1fr)]">
    <Card><CardHeader><div><CardTitle>Workspace preferences</CardTitle><p className="mt-1 text-sm text-muted-foreground">Choose how dates and new work are organised.</p></div><Settings2 className="size-5 text-muted-foreground" /></CardHeader><CardContent>{error && <p role="alert" className="mb-4 rounded-md border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}{draft && <form onSubmit={save} className="space-y-5"><div><label htmlFor="settings-timezone" className="mb-2 block text-sm font-medium">Timezone</label><input id="settings-timezone" list="settings-timezones" required maxLength={100} value={draft.timezone} onChange={(event) => setDraft({ ...draft, timezone: event.target.value })} className={fieldClass} /><datalist id="settings-timezones">{commonTimezones.map((zone) => <option key={zone} value={zone} />)}</datalist><p className="mt-2 text-xs text-muted-foreground">Used for reminders, schedule times, and date boundaries.</p></div><div><label htmlFor="settings-week" className="mb-2 block text-sm font-medium">First day of the week</label><select id="settings-week" value={draft.weekStartsOn} onChange={(event) => setDraft({ ...draft, weekStartsOn: Number(event.target.value) as 0 | 1 })} className={fieldClass}><option value={1}>Monday</option><option value={0}>Sunday</option></select></div><div><label htmlFor="settings-priority" className="mb-2 block text-sm font-medium">Default task priority</label><select id="settings-priority" value={draft.defaultTaskPriority} onChange={(event) => setDraft({ ...draft, defaultTaskPriority: event.target.value as Settings["defaultTaskPriority"] })} className={fieldClass}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select></div><div className="flex items-center justify-end gap-3 border-t pt-5">{saved && <span className="flex items-center gap-1 text-sm text-green-700"><Check className="size-4" />Saved</span>}<Button type="submit" disabled={saving || session.user.role === "viewer" || JSON.stringify(settings) === JSON.stringify(draft)}>{saving && <LoaderCircle className="size-4 animate-spin" />}{saving ? "Saving…" : "Save preferences"}</Button></div>{session.user.role === "viewer" && <p className="text-sm text-muted-foreground">Viewer accounts cannot change settings.</p>}</form>}</CardContent></Card>
    <div className="space-y-5"><Card><CardHeader><CardTitle>Account</CardTitle><UserRound className="size-5 text-muted-foreground" /></CardHeader><CardContent className="space-y-4"><div><p className="text-xs uppercase tracking-wide text-muted-foreground">Email</p><p className="mt-1 break-all text-sm font-medium">{session.user.email}</p></div><div><p className="text-xs uppercase tracking-wide text-muted-foreground">Role</p><p className="mt-1 text-sm font-medium capitalize">{session.user.role}</p></div><div><p className="text-xs uppercase tracking-wide text-muted-foreground">Environment</p><p className="mt-1 text-sm font-medium capitalize">{session.environment}</p></div></CardContent></Card><Card><CardHeader><CardTitle>Security</CardTitle><ShieldCheck className="size-5 text-green-700" /></CardHeader><CardContent><p className="text-sm leading-6 text-muted-foreground">Your dashboard uses an HTTP-only session cookie, server-side ownership checks, and trusted-origin validation.</p></CardContent></Card><Card><CardContent className="flex items-center gap-3 p-5"><Clock3 className="size-5 text-primary" /><div><p className="text-sm font-medium">Current local time</p><p className="text-xs text-muted-foreground">{draft ? new Intl.DateTimeFormat("en-AU", { dateStyle: "medium", timeStyle: "short", timeZone: draft.timezone }).format(new Date()) : "—"}</p></div></CardContent></Card></div>
  </div>
}
